### ISSUE TITLE
chybějící "settings."

### ISSUE THREAD

**Issue by Kuba799500** [vojtektomascz/keysniper#1]
https://github.com/vojtektomascz/keysniper/blob/ec6295d9e28e80bbf4491743fe299db298b547cf/keysniper.js#L348

Ahoj,
před correctTypeErrors ti chybí "settings." - díky tomu mi to házelo chybu a nefungovalo mi bezchybné psaní…

**Comment by vojtektomascz** [comment]
Opraveno, díky za upozornění :)
