### ISSUE TITLE
oprava časovače (titul stránky)

### ISSUE THREAD

**Issue by Kuba799500** [vojtektomascz/keysniper#2]
Opět zdravím :D
objevuje se mi chyba, kdy se spustí několik časovačů zároveň. Chyba se projevuje, když se napíše první znak (index 0) a poté uděláte chybu. Tím pádem zůstane index na 0 ale spustí se další časovač. Když se pak chyba opraví, spustí se ještě další časovač (tzn. jsou spuštěné 3 zároveň). Bohužel, když snímek opakujete (funkce `resetPage()`) časovače dál běží.
Proto jsem kód trošku poupravil - přidal jsem logickou proměnnou `timerActive`, která zamezuje spuštění dalšího časovače, když už jeden běží. Posílám upravený celý "odstavec" kódu:

`  if (pageUrl == "edu-typing" || catUrl == "edu" || catUrl == "grp" || catUrl == "rss") {
    let index, position, positionTemp, errors, errorsTemp, trueErrors, correct, seconds, minutes, time, active, timerActive;
    document.getElementById("copy").addEventListener("DOMSubtreeModified", function () {
      if (index == 0 && timerActive == false) {
          timerActive = true
          time = setInterval(function () {
          seconds++;
          if (seconds == 60) {
            seconds = 0;
            minutes++;
          }
          showTitle();
        }, 1000);
      }
    });
    function resetPage() {
      clearInterval(time);
      index = -1;
      position = -1;
      positionTemp = -1;
      errors = 0;
      errorsTemp = 0;
      trueErrors = 0;
      seconds = 0;
      minutes = 0;
      timerActive = false;
      showTitle();
    }
`

**Comment by vojtektomascz** [comment]
Opět děkuji za opravu, tvůj kód jsem trochu poupravil a změny jsem zveřejnil.
